import type { AlgorithmDefinition, AlgorithmStep } from '../types';

const findTheDifference: AlgorithmDefinition = {
  id: 'find-the-difference',
  title: 'Find the Difference',
  leetcodeNumber: 389,
  difficulty: 'Easy',
  category: 'Hash Map',
  description:
    'Given two strings s and t where t is generated by shuffling s and adding one extra character, find and return the added character. Use a frequency map or XOR approach to identify the extra character.',
  tags: ['hash map', 'bit manipulation', 'XOR', 'string'],

  code: {
    pseudocode: `function findTheDifference(s, t):
  count = {}
  for char in s:
    count[char] = count.get(char, 0) + 1
  for char in t:
    count[char] = count.get(char, 0) - 1
    if count[char] < 0:
      return char`,

    python: `def findTheDifference(s: str, t: str) -> str:
    from collections import Counter
    count = Counter(s)
    for c in t:
        count[c] -= 1
        if count[c] < 0:
            return c
    return ''`,

    javascript: `function findTheDifference(s, t) {
  const count = {};
  for (const c of s) count[c] = (count[c] || 0) + 1;
  for (const c of t) {
    count[c] = (count[c] || 0) - 1;
    if (count[c] < 0) return c;
  }
}`,

    java: `public char findTheDifference(String s, String t) {
    int[] count = new int[26];
    for (char c : s.toCharArray()) count[c - 'a']++;
    for (char c : t.toCharArray()) {
        count[c - 'a']--;
        if (count[c - 'a'] < 0) return c;
    }
    return 0;
}`,
  },

  defaultInput: {
    s: 'abcd',
    t: 'abcde',
  },

  inputFields: [
    {
      name: 's',
      label: 'String S',
      type: 'string',
      defaultValue: 'abcd',
      placeholder: 'abcd',
      helperText: 'Original string',
    },
    {
      name: 't',
      label: 'String T',
      type: 'string',
      defaultValue: 'abcde',
      placeholder: 'abcde',
      helperText: 'Shuffled string with one extra character added',
    },
  ],

  generateSteps(input: Record<string, unknown>): AlgorithmStep[] {
    const s = input.s as string;
    const t = input.t as string;
    const steps: AlgorithmStep[] = [];
    const count: Record<string, number> = {};

    steps.push({
      line: 1,
      explanation: `Input: s="${s}", t="${t}". Build frequency map for s, then subtract counts using t.`,
      variables: { s, t },
      visualization: {
        type: 'array',
        array: s.split('').map((_, i) => i),
        highlights: {},
        labels: Object.fromEntries(s.split('').map((c, i) => [i, c])),
      },
    });

    for (const c of s) {
      count[c] = (count[c] || 0) + 1;
    }

    steps.push({
      line: 3,
      explanation: `After counting s="${s}": ${Object.entries(count).map(([k, v]) => `"${k}":${v}`).join(', ')}`,
      variables: { ...count },
      visualization: {
        type: 'array',
        array: s.split('').map((_, i) => i),
        highlights: Object.fromEntries(s.split('').map((_, i) => [i, 'active'])),
        labels: Object.fromEntries(s.split('').map((c, i) => [i, c])),
      },
    });

    for (let i = 0; i < t.length; i++) {
      const c = t[i];
      count[c] = (count[c] || 0) - 1;

      steps.push({
        line: 6,
        explanation: `Processing t[${i}]="${c}": decrement count["${c}"] to ${count[c]}. ${count[c] < 0 ? 'Count went negative - this is the extra character!' : 'Still non-negative, continue.'}`,
        variables: { char: c, newCount: count[c], ...count },
        visualization: {
          type: 'array',
          array: t.split('').map((_, idx) => idx),
          highlights: {
            [i]: count[c] < 0 ? 'found' : 'active',
            ...Object.fromEntries(Array.from({ length: i }, (_, j) => [j, 'sorted'])),
          },
          labels: Object.fromEntries(t.split('').map((ch, idx) => [idx, ch])),
        },
      });

      if (count[c] < 0) {
        steps.push({
          line: 8,
          explanation: `count["${c}"] < 0: "${c}" is the extra character added to t. Return "${c}".`,
          variables: { result: c },
          visualization: {
            type: 'array',
            array: t.split('').map((_, idx) => idx),
            highlights: { [i]: 'found' },
            labels: Object.fromEntries(t.split('').map((ch, idx) => [idx, ch])),
          },
        });
        return steps;
      }
    }

    return steps;
  },
};

export default findTheDifference;
