import type { AlgorithmDefinition, AlgorithmStep, DPVisualization } from '../types';

const profitableSchemes: AlgorithmDefinition = {
  id: 'profitable-schemes',
  title: 'Profitable Schemes',
  leetcodeNumber: 879,
  difficulty: 'Hard',
  category: 'Dynamic Programming',
  description:
    'There are n gang members and a list of crimes. Each crime requires a certain number of members and generates a certain profit. Count the number of subsets of crimes (schemes) such that the total members used is at most n and the total profit is at least minProfit. The 3D DP approach: dp[k][members][profit] = number of ways using k crimes with at most "members" members and exactly "profit" profit. We cap profit at minProfit to avoid unbounded dimensions.',
  tags: ['dp', '3d dp', 'knapsack', 'counting', 'modular arithmetic'],

  code: {
    pseudocode: `function profitableSchemes(n, minProfit, group, profit):
  MOD = 10^9 + 7
  // dp[members][p] = number of schemes using <= members with >= p profit
  dp = 2D array (n+1) x (minProfit+1), all 0
  dp[0][0] = 1
  for each crime i:
    g = group[i], p = profit[i]
    for members from n downto g:
      for pp from minProfit downto 0:
        dp[members][min(minProfit, pp+p)] += dp[members-g][pp]
  return sum of dp[0..n][minProfit] % MOD`,
    python: `def profitableSchemes(n, minProfit, group, profit):
    MOD = 10**9 + 7
    dp = [[0]*(minProfit+1) for _ in range(n+1)]
    dp[0][0] = 1
    for g, p in zip(group, profit):
        for members in range(n, g-1, -1):
            for pp in range(minProfit, -1, -1):
                dp[members][min(minProfit, pp+p)] = \
                    (dp[members][min(minProfit,pp+p)] + dp[members-g][pp]) % MOD
    return sum(dp[m][minProfit] for m in range(n+1)) % MOD`,
    javascript: `function profitableSchemes(n, minProfit, group, profit) {
  const MOD = 1e9+7;
  const dp = Array.from({length:n+1}, ()=>new Array(minProfit+1).fill(0));
  dp[0][0] = 1;
  for (let i = 0; i < group.length; i++) {
    const g=group[i], p=profit[i];
    for (let m=n; m>=g; m--)
      for (let pp=minProfit; pp>=0; pp--)
        dp[m][Math.min(minProfit,pp+p)] = (dp[m][Math.min(minProfit,pp+p)]+dp[m-g][pp])%MOD;
  }
  return dp.reduce((s,row)=>s+row[minProfit],0)%MOD;
}`,
    java: `public int profitableSchemes(int n,int minProfit,int[] group,int[] profit){
    int MOD=1_000_000_007;
    long[][] dp=new long[n+1][minProfit+1];
    dp[0][0]=1;
    for(int i=0;i<group.length;i++){
        int g=group[i],p=profit[i];
        for(int m=n;m>=g;m--)
            for(int pp=minProfit;pp>=0;pp--){
                int np=Math.min(minProfit,pp+p);
                dp[m][np]=(dp[m][np]+dp[m-g][pp])%MOD;
            }
    }
    long ans=0;
    for(int m=0;m<=n;m++) ans=(ans+dp[m][minProfit])%MOD;
    return (int)ans;
}`,
  },

  defaultInput: {
    n: 5,
    minProfit: 3,
    group: [2, 2],
    profit: [2, 3],
  },

  inputFields: [
    {
      name: 'n',
      label: 'Gang Members (n)',
      type: 'number',
      defaultValue: 5,
      placeholder: '5',
      helperText: 'Maximum number of members to use',
    },
    {
      name: 'minProfit',
      label: 'Minimum Profit',
      type: 'number',
      defaultValue: 3,
      placeholder: '3',
      helperText: 'Minimum required profit',
    },
    {
      name: 'group',
      label: 'Members per Crime',
      type: 'array',
      defaultValue: [2, 2],
      placeholder: '2,2',
      helperText: 'Number of members required for each crime',
    },
    {
      name: 'profit',
      label: 'Profit per Crime',
      type: 'array',
      defaultValue: [2, 3],
      placeholder: '2,3',
      helperText: 'Profit generated by each crime',
    },
  ],

  generateSteps(input: Record<string, unknown>): AlgorithmStep[] {
    const n = input.n as number;
    const minProfit = input.minProfit as number;
    const group = input.group as number[];
    const profit = input.profit as number[];
    const steps: AlgorithmStep[] = [];
    const MOD = 1_000_000_007;
    const dp: number[][] = Array.from({ length: n + 1 }, () =>
      new Array(minProfit + 1).fill(0)
    );
    dp[0][0] = 1;

    const makeViz = (highlights: Record<number, string>): DPVisualization => ({
      type: 'dp-table',
      values: dp.flat(),
      highlights,
      labels: Array.from({ length: (n + 1) * (minProfit + 1) }, (_, k) => {
        const m = Math.floor(k / (minProfit + 1));
        const p = k % (minProfit + 1);
        return `m=${m},p=${p}`;
      }),
    });

    steps.push({
      line: 1,
      explanation: `n=${n} members, minProfit=${minProfit}. ${group.length} crimes. dp[m][p] = ways using m members with profit >= p.`,
      variables: { n, minProfit, crimes: group.length },
      visualization: makeViz({ 0: 'found' }),
    });

    for (let i = 0; i < group.length; i++) {
      const g = group[i];
      const p = profit[i];
      steps.push({
        line: 6,
        explanation: `Crime ${i}: requires ${g} members, yields ${p} profit. Updating DP (backwards to avoid reuse).`,
        variables: { crime: i, members: g, crimeProfit: p },
        visualization: makeViz({}),
      });

      for (let m = n; m >= g; m--) {
        for (let pp = minProfit; pp >= 0; pp--) {
          if (dp[m - g][pp] === 0) continue;
          const np = Math.min(minProfit, pp + p);
          const prevIdx = (m - g) * (minProfit + 1) + pp;
          const newIdx = m * (minProfit + 1) + np;
          dp[m][np] = (dp[m][np] + dp[m - g][pp]) % MOD;
          steps.push({
            line: 9,
            explanation: `m=${m}, pp=${pp}: dp[${m}][${np}] += dp[${m - g}][${pp}] = ${dp[m - g][pp]}. dp[${m}][${np}] = ${dp[m][np]}.`,
            variables: { m, pp, np, 'dp[m][np]': dp[m][np] },
            visualization: makeViz({ [newIdx]: 'active', [prevIdx]: 'comparing' }),
          });
        }
      }
    }

    let ans = 0;
    for (let m = 0; m <= n; m++) ans = (ans + dp[m][minProfit]) % MOD;

    steps.push({
      line: 11,
      explanation: `Sum all dp[m][${minProfit}] for m=0..${n}. Total profitable schemes = ${ans}.`,
      variables: { result: ans },
      visualization: makeViz(
        Object.fromEntries(
          Array.from({ length: n + 1 }, (_, m) => [m * (minProfit + 1) + minProfit, 'found'])
        )
      ),
    });

    return steps;
  },
};

export default profitableSchemes;
